#ifndef FITNESS_H
#define FITNESS_H

enum Fitness
{
    MAXPATHLENGTH,
    TOTALPATHDISTANCE,
    TOTALVERTICALPATHDISTANCE,
    MAXPATHTOTALPATHWEIGHTEDSUM,
    MAXPATHTOTALPATHWEIGHTEDSUMOBJECTIVE,
    HYPERVOLUME,
    DELTASPREAD,
    TIMEELAPSED
};

#endif
